Terjemahan BNPCHS 2019 - Final: Mencari Tempat Tinggal
prabowo02/tlx-translations pull request #16
Opened 2020-05-29 06:30 UTC by Berted

2020-05-29 11:51 UTC, juancarlovieri commented on translations/bnpchs-final-2019-mencari-tempat-tinggal.html
> +  The next $$$N - 1$$$ lines, each contains two integers $$$U$$$ and $$$V$$$, indicating a road between intersection $$$U$$$ and intersection $$$V$$$. <br>
```suggestion
  The next $$$N - 1$$$ lines each contains two integers $$$U$$$ and $$$V$$$, indicating a road between intersection $$$U$$$ and intersection $$$V$$$. <br>
```

2020-05-29 12:42 UTC, juancarlovieri commented on translations/bnpchs-final-2019-mencari-tempat-tinggal.html
> +  The next line contains $$$M$$$ integers, which are a list of intersections that is one of Feli's meeting spots.
```suggestion
  The last line contains $$$M$$$ integers, where each integer denotes Feli's meeting spot.
```

2020-05-29 13:52 UTC, VioAlbert requested changes

2020-05-29 13:52 UTC, VioAlbert commented on translations/bnpchs-final-2019-mencari-tempat-tinggal.html
> +</p>
setiap linenya buat tag `<p>` baru aja daripada pake `<br>` karena spacing `<br>` lebih kecil dibandingkan pake `<p>`.

2020-05-29 13:52 UTC, VioAlbert commented on translations/bnpchs-final-2019-mencari-tempat-tinggal.html
> +  Feli is a university student looking for a place to stay. The city where Feli lives in is made up of $$$N$$$ intersections connected by $$$N - 1$$$ roads. It is guaranteed that every pair of inters
line panjang seperti ini sebaiknya di pisah jadi dua line. batas kata per line sebaiknya 100 sesuai dengan yang ada di readme

2020-05-31 03:57 UTC, VioAlbert approved these changes

2020-05-31 09:07 UTC, merged